// Static snapshot of the seeded Supabase data (see supabase/migrations/*.sql).
// Used as a dependency-free fallback so the site renders correctly on any
// deployment (e.g. a Vercel preview) that hasn't been given Supabase
// credentials yet. If/when Supabase is wired back in, this file can be
// deleted and destinations.functions.ts reverted to query the database.
import type { CategoryDTO, DestinationDTO } from "./destinations.functions";

export const staticCategories: CategoryDTO[] = [
  { id: "nature", slug: "nature", name: "Nature", icon: "leaf", color: "#4ade80", sort: 1 },
  { id: "historical", slug: "historical", name: "Historical Sites", icon: "landmark", color: "#f59e0b", sort: 2 },
  { id: "museums", slug: "museums", name: "Museums", icon: "archive", color: "#a78bfa", sort: 3 },
  { id: "religious", slug: "religious", name: "Religious", icon: "moon", color: "#38bdf8", sort: 4 },
  { id: "culture", slug: "culture", name: "Culture", icon: "drama", color: "#f472b6", sort: 5 },
  { id: "shopping", slug: "shopping", name: "Shopping", icon: "shopping-bag", color: "#fb7185", sort: 6 },
  { id: "culinary", slug: "culinary", name: "Culinary", icon: "utensils", color: "#fbbf24", sort: 7 },
  { id: "hotels", slug: "hotels", name: "Hotels", icon: "bed", color: "#94a3b8", sort: 8 },
  { id: "transport", slug: "transport", name: "Transportation", icon: "bus", color: "#60a5fa", sort: 9 },
  { id: "public", slug: "public", name: "Public Facilities", icon: "building-2", color: "#cbd5e1", sort: 10 },
  { id: "photo", slug: "photo", name: "Photography Spots", icon: "camera", color: "#22d3ee", sort: 11 },
  { id: "entertainment", slug: "entertainment", name: "Entertainment", icon: "music", color: "#c084fc", sort: 12 },
];

const catBySlug = new Map(staticCategories.map((c) => [c.slug, c]));

function dest(
  d: Omit<DestinationDTO, "id" | "category_id" | "category_slug" | "category_name" | "category_color"> & {
    category_slug: string;
  },
): DestinationDTO {
  const cat = catBySlug.get(d.category_slug)!;
  return {
    ...d,
    id: d.slug,
    category_id: cat.id,
    category_slug: cat.slug,
    category_name: cat.name,
    category_color: cat.color,
  };
}

export const staticDestinations: DestinationDTO[] = [
  dest({
    slug: "candi-pari",
    name: "Candi Pari",
    category_slug: "historical",
    district: "Porong",
    village: "Candipari",
    lat: -7.5389,
    lng: 112.7017,
    hero_image: "/images/candi-pari.jpg",
    short_desc: "14th-century Majapahit brick temple rising from the rice fields.",
    description:
      "Built in 1371 during the reign of King Hayam Wuruk, Candi Pari is a red-brick Hindu temple standing 13 meters tall. Its terraced base and slender silhouette reflect the northern Javanese style of Majapahit sacred architecture.",
    opening_hours: "07:00 - 17:00",
    ticket_price: "Free",
    rating: 4.7,
    duration_minutes: 60,
    website: null,
    google_maps_url: "https://maps.google.com/?q=-7.5389,112.7017",
    tags: ["heritage", "majapahit", "temple"],
    is_popular: true,
    is_free: true,
    is_family_friendly: true,
    is_hidden_gem: false,
    is_new: false,
    is_accessible: true,
    is_night: false,
    chapter_order: 2,
  }),
  dest({
    slug: "jayandaru",
    name: "Monumen Jayandaru",
    category_slug: "historical",
    district: "Kota Sidoarjo",
    village: "Sidokumpul",
    lat: -7.4478,
    lng: 112.7183,
    hero_image: "/images/jayandaru.jpg",
    short_desc: "The luminous heart of Sidoarjo alun-alun after dusk.",
    description:
      "A modern monument at the town square depicting a farmer, a fisherman, and a shrimp — the three symbols on Sidoarjo's coat of arms — celebrating the delta's livelihoods.",
    opening_hours: "24 hours",
    ticket_price: "Free",
    rating: 4.6,
    duration_minutes: 30,
    website: null,
    google_maps_url: "https://maps.google.com/?q=-7.4478,112.7183",
    tags: ["landmark", "night", "photo"],
    is_popular: true,
    is_free: true,
    is_family_friendly: true,
    is_hidden_gem: false,
    is_new: false,
    is_accessible: true,
    is_night: true,
    chapter_order: 7,
  }),
  dest({
    slug: "batik-jetis",
    name: "Kampung Batik Jetis",
    category_slug: "culture",
    district: "Sidoarjo",
    village: "Jetis",
    lat: -7.4622,
    lng: 112.7167,
    hero_image: "/images/batik-jetis.jpg",
    short_desc: "Centuries-old canting workshops where wax meets silk.",
    description:
      "Since 1859, Jetis village has been a living workshop of hand-drawn batik tulis. Visitors can watch artisans dip canting into hot wax and buy directly from the makers.",
    opening_hours: "08:00 - 17:00",
    ticket_price: "Free entry",
    rating: 4.6,
    duration_minutes: 90,
    website: null,
    google_maps_url: "https://maps.google.com/?q=-7.4622,112.7167",
    tags: ["craft", "shopping", "heritage"],
    is_popular: true,
    is_free: true,
    is_family_friendly: true,
    is_hidden_gem: false,
    is_new: false,
    is_accessible: false,
    is_night: false,
    chapter_order: 4,
  }),
  dest({
    slug: "tlocor-mangrove",
    name: "Tlocor Mangrove",
    category_slug: "nature",
    district: "Jabon",
    village: "Kedungpandan",
    lat: -7.5561,
    lng: 112.8514,
    hero_image: "/images/mangrove.jpg",
    short_desc: "Boardwalks through migratory bird sanctuaries.",
    description:
      "A living seawall of mangroves protecting the eastern coast, laced with wooden boardwalks, birdwatching towers and boat rides to Lusi Island at the river mouth.",
    opening_hours: "06:00 - 18:00",
    ticket_price: "IDR 10,000",
    rating: 4.5,
    duration_minutes: 180,
    website: null,
    google_maps_url: "https://maps.google.com/?q=-7.5561,112.8514",
    tags: ["nature", "birds", "ecotourism"],
    is_popular: false,
    is_free: false,
    is_family_friendly: true,
    is_hidden_gem: true,
    is_new: false,
    is_accessible: false,
    is_night: false,
    chapter_order: 3,
  }),
  dest({
    slug: "delta-fishing",
    name: "Delta Fishing",
    category_slug: "entertainment",
    district: "Prambon",
    village: "Watutulis",
    lat: -7.4667,
    lng: 112.6167,
    hero_image: "/images/delta-fishing.jpg",
    short_desc: "Wooden jetties and pond fishing beneath open skies.",
    description:
      "A family recreation park with fishing ponds, floating restaurants, ATV trails and a small water park on the edge of the delta's rice fields.",
    opening_hours: "08:00 - 17:00",
    ticket_price: "IDR 25,000",
    rating: 4.4,
    duration_minutes: 240,
    website: null,
    google_maps_url: "https://maps.google.com/?q=-7.4667,112.6167",
    tags: ["adventure", "family", "fishing"],
    is_popular: true,
    is_free: false,
    is_family_friendly: true,
    is_hidden_gem: false,
    is_new: false,
    is_accessible: false,
    is_night: false,
    chapter_order: null,
  }),
  dest({
    slug: "museum-mpu-tantular",
    name: "Museum Mpu Tantular",
    category_slug: "museums",
    district: "Buduran",
    village: "Sidokerto",
    lat: -7.4106,
    lng: 112.725,
    hero_image: "/images/museum.jpg",
    short_desc: "East Java's living archive of pre-Islamic Java.",
    description:
      "Relocated to Buduran in 2003, this museum houses more than 15,000 artifacts spanning prehistory, the Hindu-Buddhist kingdoms, Islamic sultanates and the Dutch colonial era.",
    opening_hours: "08:00 - 15:00",
    ticket_price: "IDR 4,000",
    rating: 4.5,
    duration_minutes: 120,
    website: null,
    google_maps_url: "https://maps.google.com/?q=-7.4106,112.7250",
    tags: ["history", "artifacts", "education"],
    is_popular: true,
    is_free: false,
    is_family_friendly: true,
    is_hidden_gem: false,
    is_new: false,
    is_accessible: true,
    is_night: false,
    chapter_order: 5,
  }),
  dest({
    slug: "masjid-agung",
    name: "Masjid Agung Sidoarjo",
    category_slug: "religious",
    district: "Kota Sidoarjo",
    village: "Alun-alun",
    lat: -7.4483,
    lng: 112.7178,
    hero_image: "/images/jayandaru.jpg",
    short_desc: "A twin-minaret mosque anchoring the town square.",
    description:
      "The Great Mosque of Sidoarjo sits on the western side of the alun-alun. Its blue dome and slim minarets are illuminated at maghrib each evening.",
    opening_hours: "04:00 - 21:00",
    ticket_price: "Free",
    rating: 4.8,
    duration_minutes: 45,
    website: null,
    google_maps_url: "https://maps.google.com/?q=-7.4483,112.7178",
    tags: ["religious", "landmark", "architecture"],
    is_popular: true,
    is_free: true,
    is_family_friendly: true,
    is_hidden_gem: false,
    is_new: false,
    is_accessible: true,
    is_night: false,
    chapter_order: null,
  }),
  dest({
    slug: "alun-alun",
    name: "Alun-alun Sidoarjo",
    category_slug: "public",
    district: "Kota Sidoarjo",
    village: "Sidokumpul",
    lat: -7.4478,
    lng: 112.718,
    hero_image: "/images/jayandaru.jpg",
    short_desc: "The living heart of the city, day and night.",
    description:
      "A grassy square ringed by the great mosque, the regent's office, and the Jayandaru monument. Street food carts and buskers gather here every evening.",
    opening_hours: "24 hours",
    ticket_price: "Free",
    rating: 4.6,
    duration_minutes: 60,
    website: null,
    google_maps_url: "https://maps.google.com/?q=-7.4478,112.7180",
    tags: ["landmark", "family", "night"],
    is_popular: true,
    is_free: true,
    is_family_friendly: true,
    is_hidden_gem: false,
    is_new: false,
    is_accessible: true,
    is_night: true,
    chapter_order: null,
  }),
  dest({
    slug: "suncity-mall",
    name: "Suncity Mall",
    category_slug: "shopping",
    district: "Kota Sidoarjo",
    village: "Pucang",
    lat: -7.4506,
    lng: 112.715,
    hero_image: "/images/jayandaru.jpg",
    short_desc: "The regency's largest shopping and dining anchor.",
    description:
      "A four-level mall with a cineplex, food hall, and department stores — a convenient rainy-day stop between temples and mangroves.",
    opening_hours: "10:00 - 22:00",
    ticket_price: "Free entry",
    rating: 4.4,
    duration_minutes: 180,
    website: null,
    google_maps_url: "https://maps.google.com/?q=-7.4506,112.7150",
    tags: ["shopping", "indoor", "family"],
    is_popular: true,
    is_free: true,
    is_family_friendly: true,
    is_hidden_gem: false,
    is_new: false,
    is_accessible: true,
    is_night: false,
    chapter_order: null,
  }),
  dest({
    slug: "kupang-lontong",
    name: "Kupang Lontong Balongdowo",
    category_slug: "culinary",
    district: "Candi",
    village: "Balongdowo",
    lat: -7.4839,
    lng: 112.7397,
    hero_image: "/images/lontong-kupang.jpg",
    short_desc: "The delta's signature dish, in the village that raises it.",
    description:
      "Balongdowo is the village of the kupang harvesters. Tiny clams from the delta are ladled over rice cakes with lentho, coconut sauce and lime — served at open warungs along the road.",
    opening_hours: "07:00 - 21:00",
    ticket_price: "IDR 15,000",
    rating: 4.7,
    duration_minutes: 45,
    website: null,
    google_maps_url: "https://maps.google.com/?q=-7.4839,112.7397",
    tags: ["culinary", "local", "signature"],
    is_popular: true,
    is_free: false,
    is_family_friendly: true,
    is_hidden_gem: true,
    is_new: false,
    is_accessible: false,
    is_night: false,
    chapter_order: 6,
  }),
  dest({
    slug: "bandeng-asap",
    name: "Bandeng Asap Sidoarjo",
    category_slug: "culinary",
    district: "Kota Sidoarjo",
    village: "Pekauman",
    lat: -7.4522,
    lng: 112.7194,
    hero_image: "/images/bandeng.jpg",
    short_desc: "Boneless smoked milkfish — the delta's edible passport.",
    description:
      "Sidoarjo is the shrimp and milkfish capital of East Java. Bandeng asap is the take-home version: whole boneless milkfish, cold-smoked over coconut husks and vacuum-sealed.",
    opening_hours: "08:00 - 20:00",
    ticket_price: "IDR 40,000",
    rating: 4.6,
    duration_minutes: 30,
    website: null,
    google_maps_url: "https://maps.google.com/?q=-7.4522,112.7194",
    tags: ["culinary", "souvenir"],
    is_popular: true,
    is_free: false,
    is_family_friendly: true,
    is_hidden_gem: false,
    is_new: false,
    is_accessible: true,
    is_night: false,
    chapter_order: 6,
  }),
  dest({
    slug: "terminal-purabaya",
    name: "Terminal Purabaya (Bungurasih)",
    category_slug: "transport",
    district: "Waru",
    village: "Bungurasih",
    lat: -7.3556,
    lng: 112.7292,
    hero_image: "/images/jayandaru.jpg",
    short_desc: "The largest bus terminal in Southeast Asia — Sidoarjo's gateway.",
    description:
      "The main long-distance bus terminal serving Surabaya metropolitan area, located inside Sidoarjo Regency. Air-conditioned executive buses run from here to Bali, Yogyakarta and Jakarta.",
    opening_hours: "24 hours",
    ticket_price: "Free",
    rating: 4.0,
    duration_minutes: 30,
    website: null,
    google_maps_url: "https://maps.google.com/?q=-7.3556,112.7292",
    tags: ["gateway", "transit"],
    is_popular: false,
    is_free: true,
    is_family_friendly: true,
    is_hidden_gem: false,
    is_new: false,
    is_accessible: true,
    is_night: false,
    chapter_order: null,
  }),
  dest({
    slug: "kahuripan-nirwana",
    name: "Kahuripan Nirwana Lake",
    category_slug: "photo",
    district: "Sidoarjo",
    village: "Entalsewu",
    lat: -7.4269,
    lng: 112.7331,
    hero_image: "/images/mangrove.jpg",
    short_desc: "A mirror lake framed by a modern township.",
    description:
      "A landscaped lake at the heart of Sidoarjo's newest township — a favorite spot for golden-hour photography, jogging and outdoor cafés.",
    opening_hours: "24 hours",
    ticket_price: "Free",
    rating: 4.5,
    duration_minutes: 60,
    website: null,
    google_maps_url: "https://maps.google.com/?q=-7.4269,112.7331",
    tags: ["photo", "sunset", "urban"],
    is_popular: false,
    is_free: true,
    is_family_friendly: true,
    is_hidden_gem: false,
    is_new: true,
    is_accessible: true,
    is_night: false,
    chapter_order: null,
  }),
  dest({
    slug: "sun-hotel",
    name: "Sun Hotel Sidoarjo",
    category_slug: "hotels",
    district: "Kota Sidoarjo",
    village: "Pucang",
    lat: -7.455,
    lng: 112.7161,
    hero_image: "/images/jayandaru.jpg",
    short_desc: "A four-star anchor for the delta traveler.",
    description:
      "A 155-room business hotel with a rooftop pool overlooking the alun-alun and the great mosque — a comfortable base for two- or three-day journeys.",
    opening_hours: "24 hours",
    ticket_price: "From IDR 550,000 / night",
    rating: 4.4,
    duration_minutes: null,
    website: null,
    google_maps_url: "https://maps.google.com/?q=-7.4550,112.7161",
    tags: ["hotel", "4-star", "pool"],
    is_popular: true,
    is_free: false,
    is_family_friendly: true,
    is_hidden_gem: false,
    is_new: false,
    is_accessible: true,
    is_night: false,
    chapter_order: null,
  }),
];
