
INSERT INTO public.categories (slug, name, icon, color, sort) VALUES
('nature','Nature','leaf','#4ade80',1),
('historical','Historical Sites','landmark','#f59e0b',2),
('museums','Museums','archive','#a78bfa',3),
('religious','Religious','moon','#38bdf8',4),
('culture','Culture','drama','#f472b6',5),
('shopping','Shopping','shopping-bag','#fb7185',6),
('culinary','Culinary','utensils','#fbbf24',7),
('hotels','Hotels','bed','#94a3b8',8),
('transport','Transportation','bus','#60a5fa',9),
('public','Public Facilities','building-2','#cbd5e1',10),
('photo','Photography Spots','camera','#22d3ee',11),
('entertainment','Entertainment','music','#c084fc',12);

INSERT INTO public.destinations (slug, name, category_id, district, village, lat, lng, hero_image, short_desc, description, opening_hours, ticket_price, rating, duration_minutes, google_maps_url, tags, is_popular, is_free, is_family_friendly, is_hidden_gem, is_new, is_accessible, chapter_order) VALUES
('candi-pari', 'Candi Pari', (SELECT id FROM public.categories WHERE slug='historical'),'Porong','Candipari',-7.5389,112.7017,'/images/candi-pari.jpg','14th-century Majapahit brick temple rising from the rice fields.','Built in 1371 during the reign of King Hayam Wuruk, Candi Pari is a red-brick Hindu temple standing 13 meters tall. Its terraced base and slender silhouette reflect the northern Javanese style of Majapahit sacred architecture.','07:00 - 17:00','Free','4.7',60,'https://maps.google.com/?q=-7.5389,112.7017',ARRAY['heritage','majapahit','temple'],true,true,true,false,false,true,2),
('jayandaru', 'Monumen Jayandaru', (SELECT id FROM public.categories WHERE slug='historical'),'Kota Sidoarjo','Sidokumpul',-7.4478,112.7183,'/images/jayandaru.jpg','The luminous heart of Sidoarjo alun-alun after dusk.','A modern monument at the town square depicting a farmer, a fisherman, and a shrimp — the three symbols on Sidoarjo''s coat of arms — celebrating the delta''s livelihoods.','24 hours','Free','4.6',30,'https://maps.google.com/?q=-7.4478,112.7183',ARRAY['landmark','night','photo'],true,true,true,false,false,true,7),
('batik-jetis', 'Kampung Batik Jetis', (SELECT id FROM public.categories WHERE slug='culture'),'Sidoarjo','Jetis',-7.4622,112.7167,'/images/batik-jetis.jpg','Centuries-old canting workshops where wax meets silk.','Since 1859, Jetis village has been a living workshop of hand-drawn batik tulis. Visitors can watch artisans dip canting into hot wax and buy directly from the makers.','08:00 - 17:00','Free entry','4.6',90,'https://maps.google.com/?q=-7.4622,112.7167',ARRAY['craft','shopping','heritage'],true,true,true,false,false,false,4),
('tlocor-mangrove', 'Tlocor Mangrove', (SELECT id FROM public.categories WHERE slug='nature'),'Jabon','Kedungpandan',-7.5561,112.8514,'/images/mangrove.jpg','Boardwalks through migratory bird sanctuaries.','A living seawall of mangroves protecting the eastern coast, laced with wooden boardwalks, birdwatching towers and boat rides to Lusi Island at the river mouth.','06:00 - 18:00','IDR 10,000','4.5',180,'https://maps.google.com/?q=-7.5561,112.8514',ARRAY['nature','birds','ecotourism'],false,false,true,true,false,false,3),
('delta-fishing', 'Delta Fishing', (SELECT id FROM public.categories WHERE slug='entertainment'),'Prambon','Watutulis',-7.4667,112.6167,'/images/delta-fishing.jpg','Wooden jetties and pond fishing beneath open skies.','A family recreation park with fishing ponds, floating restaurants, ATV trails and a small water park on the edge of the delta''s rice fields.','08:00 - 17:00','IDR 25,000','4.4',240,'https://maps.google.com/?q=-7.4667,112.6167',ARRAY['adventure','family','fishing'],true,false,true,false,false,false,NULL),
('museum-mpu-tantular', 'Museum Mpu Tantular', (SELECT id FROM public.categories WHERE slug='museums'),'Buduran','Sidokerto',-7.4106,112.7250,'/images/museum.jpg','East Java''s living archive of pre-Islamic Java.','Relocated to Buduran in 2003, this museum houses more than 15,000 artifacts spanning prehistory, the Hindu-Buddhist kingdoms, Islamic sultanates and the Dutch colonial era.','08:00 - 15:00','IDR 4,000','4.5',120,'https://maps.google.com/?q=-7.4106,112.7250',ARRAY['history','artifacts','education'],true,false,true,false,false,true,5),
('masjid-agung', 'Masjid Agung Sidoarjo', (SELECT id FROM public.categories WHERE slug='religious'),'Kota Sidoarjo','Alun-alun',-7.4483,112.7178,'/images/jayandaru.jpg','A twin-minaret mosque anchoring the town square.','The Great Mosque of Sidoarjo sits on the western side of the alun-alun. Its blue dome and slim minarets are illuminated at maghrib each evening.','04:00 - 21:00','Free','4.8',45,'https://maps.google.com/?q=-7.4483,112.7178',ARRAY['religious','landmark','architecture'],true,true,true,false,false,true,NULL),
('alun-alun', 'Alun-alun Sidoarjo', (SELECT id FROM public.categories WHERE slug='public'),'Kota Sidoarjo','Sidokumpul',-7.4478,112.7180,'/images/jayandaru.jpg','The living heart of the city, day and night.','A grassy square ringed by the great mosque, the regent''s office, and the Jayandaru monument. Street food carts and buskers gather here every evening.','24 hours','Free','4.6',60,'https://maps.google.com/?q=-7.4478,112.7180',ARRAY['landmark','family','night'],true,true,true,false,false,true,NULL),
('suncity-mall', 'Suncity Mall', (SELECT id FROM public.categories WHERE slug='shopping'),'Kota Sidoarjo','Pucang',-7.4506,112.7150,'/images/jayandaru.jpg','The regency''s largest shopping and dining anchor.','A four-level mall with a cineplex, food hall, and department stores — a convenient rainy-day stop between temples and mangroves.','10:00 - 22:00','Free entry','4.4',180,'https://maps.google.com/?q=-7.4506,112.7150',ARRAY['shopping','indoor','family'],true,true,true,false,false,true,NULL),
('kupang-lontong', 'Kupang Lontong Balongdowo', (SELECT id FROM public.categories WHERE slug='culinary'),'Candi','Balongdowo',-7.4839,112.7397,'/images/lontong-kupang.jpg','The delta''s signature dish, in the village that raises it.','Balongdowo is the village of the kupang harvesters. Tiny clams from the delta are ladled over rice cakes with lentho, coconut sauce and lime — served at open warungs along the road.','07:00 - 21:00','IDR 15,000','4.7',45,'https://maps.google.com/?q=-7.4839,112.7397',ARRAY['culinary','local','signature'],true,false,true,true,false,false,6),
('bandeng-asap', 'Bandeng Asap Sidoarjo', (SELECT id FROM public.categories WHERE slug='culinary'),'Kota Sidoarjo','Pekauman',-7.4522,112.7194,'/images/bandeng.jpg','Boneless smoked milkfish — the delta''s edible passport.','Sidoarjo is the shrimp and milkfish capital of East Java. Bandeng asap is the take-home version: whole boneless milkfish, cold-smoked over coconut husks and vacuum-sealed.','08:00 - 20:00','IDR 40,000','4.6',30,'https://maps.google.com/?q=-7.4522,112.7194',ARRAY['culinary','souvenir'],true,false,true,false,false,true,6),
('terminal-purabaya', 'Terminal Purabaya (Bungurasih)', (SELECT id FROM public.categories WHERE slug='transport'),'Waru','Bungurasih',-7.3556,112.7292,'/images/jayandaru.jpg','The largest bus terminal in Southeast Asia — Sidoarjo''s gateway.','The main long-distance bus terminal serving Surabaya metropolitan area, located inside Sidoarjo Regency. Air-conditioned executive buses run from here to Bali, Yogyakarta and Jakarta.','24 hours','Free','4.0',30,'https://maps.google.com/?q=-7.3556,112.7292',ARRAY['gateway','transit'],false,true,true,false,false,true,NULL),
('kahuripan-nirwana', 'Kahuripan Nirwana Lake', (SELECT id FROM public.categories WHERE slug='photo'),'Sidoarjo','Entalsewu',-7.4269,112.7331,'/images/mangrove.jpg','A mirror lake framed by a modern township.','A landscaped lake at the heart of Sidoarjo''s newest township — a favorite spot for golden-hour photography, jogging and outdoor cafés.','24 hours','Free','4.5',60,'https://maps.google.com/?q=-7.4269,112.7331',ARRAY['photo','sunset','urban'],false,true,true,false,true,true,NULL),
('sun-hotel', 'Sun Hotel Sidoarjo', (SELECT id FROM public.categories WHERE slug='hotels'),'Kota Sidoarjo','Pucang',-7.4550,112.7161,'/images/jayandaru.jpg','A four-star anchor for the delta traveler.','A 155-room business hotel with a rooftop pool overlooking the alun-alun and the great mosque — a comfortable base for two- or three-day journeys.','24 hours','From IDR 550,000 / night','4.4',NULL,'https://maps.google.com/?q=-7.4550,112.7161',ARRAY['hotel','4-star','pool'],true,false,true,false,false,true,NULL);
